### ISSUE TITLE
Markdown code blocks on site do not escape characters correctly

### ISSUE THREAD

**Issue by bendiy** [pgxn/pgxn-site#10]
Having an issue with this page:
https://pgxn.org/dist/plv8/doc/plv8.html

Rendering this file:
https://github.com/plv8/plv8/blob/master/doc/plv8.md

See issue here:
https://github.com/plv8/plv8/issues/216

**Comment by theory** [comment]
This is happening because the Markdown in that file uses the triple-backtick verbatim format, which is not standard Markdown, and the `<` in `for(var i=0; i<keys.length; i++){` is not escaped. This makes for invalid HTML, which the PGXN HTML parser then chokes on (it requires valid HTML in order to do proper sanitizing of the output, e.g., removing script tags). The triple-backtick format is supported by neither the [Markdown](https://metacpan.org/release/Text-Markdown) nor the [MultiMarkdown](http://fletcherpenney.net/multimarkdown/) libraries that PGXN uses. The fix, then, is to replace those that format with standard Markdown indentation. [Done here](https://github.com/plv8/plv8/pull/232).
